verb=(input("enter a verb="))
adjective1=(input("enter a adjective1="))
adjective2=(input("enter a adjective2="))
noun=(input("enter a noun="))
print(f"the zoo is {adjective1}")
print(f"{adjective1} zoo as an animal {noun}")
print(f"that {noun} is {adjective2} & {verb}")